### ISSUE TITLE
Serial does not work

### ISSUE THREAD

**Issue by karelv** [sparkfunX/Qwiic_USB_Bridge#2]
This is a lovely product. I have put in my sketch and it didn't print anything on the console.

```cpp
void setup()
{
  Serial.begin(115200);  // Start serial for output
}

void loop()
{
  Serial.println("TEST");
  delay(500);
}
```

The compilation and upload goes well:
```
Sketch uses 10436 bytes (3%) of program storage space. Maximum is 262144 bytes.
Global variables use 2980 bytes (9%) of dynamic memory, leaving 29788 bytes for local variables. Maximum is 32768 bytes.
Atmel SMART device 0x10010005 found
Device       : ATSAMD21G18A
Chip ID      : 10010005
Version      : v1.1 [Arduino:XYZ] Jul 25 2022 23:50:06
Address      : 8192
Pages        : 3968
Page Size    : 64 bytes
Total Size   : 248KB
Planes       : 1
Lock Regions : 16
Locked       : none
Security     : false
Boot Flash   : true
BOD          : true
BOR          : true
Arduino      : FAST_CHIP_ERASE
Arduino      : FAST_MULTI_PAGE_WRITE
Arduino      : CAN_CHECKSUM_MEMORY_BUFFER
Erase flash
done in 0.814 seconds

Write 10436 bytes to flash (164 pages)

[===========                   ] 39% (64/164 pages)
[=======================       ] 78% (128/164 pages)
[==============================] 100% (164/164 pages)
done in 0.084 seconds

Verify 10436 bytes of flash with checksum.
Verify successful
done in 0.015 seconds
CPU reset.
```

The terminal stays empty:
<img width="919" alt="image" src="https://github.com/sparkfunX/Qwiic_USB_Bridge/assets/787006/5a736e37-31b1-4c7d-969b-298a585822c2">

I'm using Arduino IDE 2.2.1, with the board library:
<img width="543" alt="image" src="https://github.com/sparkfunX/Qwiic_USB_Bridge/assets/787006/748fffaa-d41b-46e7-a913-2e050c77cf4f">

Can you help to get this basic function up and running?

**Comment by nseidle** [comment]
Serial points at the physical UART where you are looking at the USB terminal. You will likely need to use SerialUSB.print().

**Comment by karelv** [comment]
`SerialUSB` indeed works... It is a little strange as all the other boards I have used are using 'Serial' for their USB one, and Serial1, Serial2, ... for the physical UARTs. But ok, it works! Thanks for pointing this out so quickly.
